# Copy this file to `config.yaml` and set the configuration items

sync:
  garmin:
    authentication_domain: CN #  Global (default) | CN (Mainland China)
    email: 842380666@qq.com
    password: Cuibowen123
